name: Continuous integration/test
on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - uses: actions/checkout@v1

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install -g coffeescript
          npm install

      - name: Compile
        run: npm run compile

      - name: Testing
        run: npm test
